# Generated by Django 4.2 on 2023-09-30 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weight',
            name='user',
        ),
    ]
