# Generated by Django 4.2 on 2023-09-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_num_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
