# Generated by Django 4.2 on 2023-09-30 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_event_description_alter_event_id'),
        ('event', '0004_alter_event_id'),
    ]

    operations = [
    ]
