# Generated by Django 4.2 on 2023-09-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_merge_20230929_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
