# Generated by Django 4.2 on 2023-09-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0002_remove_weight_user'),
        ('user', '0002_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tags',
        ),
        migrations.AddField(
            model_name='user',
            name='weights',
            field=models.ManyToManyField(blank=True, to='weight.weight'),
        ),
    ]
